version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html

  app:
    image: node:18                   # Use the official Node.js 18 image
    working_dir: /usr/src/app         # Set the working directory inside the container
    volumes:
      - ./dist:/usr/src/app           # Mount the 'dist' folder (where the built files are stored)
    command: node server.js           # Start the app from the 'dist' folder using node
    ports:
      - "3000:3000"                   # Expose port 3000
