services:
  app:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: /bin/sh -c "npm install && npm start"  # Install dependencies and then start the app
    ports:
      - "3000:3000"
