version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html
  app:
    build: .
    working_dir: /usr/src/app
    volumes:
      - ./dist:/usr/src/app
    command: node dist/server.js
    ports:
      - "3000:3000"
