version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html

  app:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - /var/jenkins_home/workspace/BankingAppPipeline2/dist:/usr/src/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
